spring.application.name=Orkestro

# Liquibase changelog
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://localhost:5432/orkestro
spring.datasource.username=postgres
spring.datasource.password=pgpwd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
