package io.github.Romariok.orkestro.notification.models.enums;

public enum InAppNotificationType {
    NEW_INFO_MESSAGE,
    NEW_EVENT,
    RSVP_REQUEST,
    NEW_TASK,
    REMINDER,
    EVENT_COMMENT,
    TASK_STATUS_CHANGED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_ASSIGNEE_ADDED,
    TASK_ASSIGNEE_REMOVED,
    TASK_DEADLINE_OVERDUE,
    JOIN_REQUEST_RECEIVED,
    JOIN_REQUEST_APPROVED,
    JOIN_REQUEST_REJECTED,
    ROLE_ASSIGNED,
    ROLE_REMOVED
}
